name = "fuelnfreetime"
main = "src/index.js"
compatibility_date = "2025-04-01"

[vars]
APP_NAME = "Fuel & Free Time"
APP_DOMAIN = "fuelnfreetime.com"
ALLOWED_ORIGINS = "https://fuelnfreetime.com"

[[d1_databases]]
binding = "DB"
database_name = "fuelnfreetime"
database_id = "9fd6ff92-e407-4b51-8b01-3c93f3845bb2"

[ai]
binding = "AGENTSAM_WAI"

[[r2_buckets]]
binding = "WEBSITE_ASSETS"
bucket_name = "fuelnfreetime"

[[kv_namespaces]]
binding = "CMS_CACHE"
id = "bc3b4e3f272e4b46b3c92df6dff85bff"
