-- GENERATED from the 23 current R2 section documents on 2026-10-07.
-- Conservative rule: only repeated numbered sibling objects become blocks.
-- Renderer/editor logic is unchanged; this only populates cms_section_blocks.

UPDATE cms_page_sections SET section_type='hero', metadata_json=json_set(metadata_json,'$.legacy_editor_template_key','hero') WHERE legacy_section_id=28;
UPDATE cms_page_sections SET section_type='hero', metadata_json=json_set(metadata_json,'$.legacy_editor_template_key','hero') WHERE legacy_section_id=29;

INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_10_f1',cs.account_id,cs.id,'f1','f',10,'active','{"title":"Hunt Drops","text":"Exclusive scavenger hunts for limited gear"}','$.content.f1','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/community.json","family":"f","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=10 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='f1');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_10_f2',cs.account_id,cs.id,'f2','f',20,'active','{"title":"Garage Nights","text":"Monthly meetups in Lafayette and beyond"}','$.content.f2','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/community.json","family":"f","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=10 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='f2');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_10_f3',cs.account_id,cs.id,'f3','f',30,'active','{"title":"Fuel Stops","text":"Pop-ups where stories meet the road"}','$.content.f3','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/community.json","family":"f","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=10 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='f3');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_10_f4',cs.account_id,cs.id,'f4','f',40,'active','{"title":"Early Access","text":"First dibs on every limited release"}','$.content.f4','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/community.json","family":"f","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=10 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='f4');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_14_card1',cs.account_id,cs.id,'card1','card',10,'active','{"name":"High Octane Collection","imageUrl":"/media/archive/shopify-import/graphics/high_octane.jpg","href":"#fft-grid"}','$.content.card1','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/shop/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=14 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card1');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_14_card2',cs.account_id,cs.id,'card2','card',20,'active','{"name":"Masters Collection","imageUrl":"/media/archive/shopify-import/graphics/Masters.png","href":"#fft-grid"}','$.content.card2','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/shop/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=14 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card2');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_14_card3',cs.account_id,cs.id,'card3','card',30,'active','{"name":"Everyday Essentials","imageUrl":"/media/archive/shopify-import/graphics/Gone_Fishing.png","href":"#fft-grid"}','$.content.card3','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/shop/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=14 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card3');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_19_card1',cs.account_id,cs.id,'card1','card',10,'active','{"title":"Fuel & Free Time Core Collection","imageUrl":"/media/archive/shopify-import/graphics/50C9CEB5.png"}','$.content.card1','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/about/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=19 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card1');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_19_card2',cs.account_id,cs.id,'card2','card',20,'active','{"title":"High Octane Performance Collection","imageUrl":"/media/archive/shopify-import/graphics/Vette.png"}','$.content.card2','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/about/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=19 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card2');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_19_card3',cs.account_id,cs.id,'card3','card',30,'active','{"title":"Masters Series Limited Edition","imageUrl":"/media/archive/shopify-import/graphics/fuel_up.png"}','$.content.card3','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/about/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=19 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card3');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_8_card1',cs.account_id,cs.id,'card1','card',10,'active','{"name":"High Octane","description":"Performance gear for redline living","imageUrl":"/media/archive/shopify-import/graphics/high_octane.jpg","href":"/collections/high-octane-performance-gear"}','$.content.card1','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=8 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card1');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_8_card2',cs.account_id,cs.id,'card2','card',20,'active','{"name":"Masters","description":"For those who''ve earned their stripes","imageUrl":"/media/archive/shopify-import/graphics/Masters.png","href":"/collections/masters"}','$.content.card2','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=8 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card2');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_8_card3',cs.account_id,cs.id,'card3','card',30,'active','{"name":"Essentials","description":"Daily drivers for the daily grind","imageUrl":"/media/archive/shopify-import/graphics/Gone_Fishing.png","href":"/collections/essentials"}','$.content.card3','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/collections.json","family":"card","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=8 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='card3');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_9_v1',cs.account_id,cs.id,'v1','v',10,'active','{"title":"Earned Not Given","description":"Every thread tells a story of hard work and dedication. This isn''t fast fashion — it''s a lifestyle earned through years of grinding."}','$.content.v1','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/values.json","family":"v","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=9 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='v1');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_9_v2',cs.account_id,cs.id,'v2','v',20,'active','{"title":"Built in Lafayette","description":"Proudly designed, cut, sewn & shipped From the heart of Louisiana. Supporting local means building something real in a world of dropshipped dreams."}','$.content.v2','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/values.json","family":"v","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=9 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='v2');
INSERT INTO cms_section_blocks (id,account_id,section_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json) SELECT 'cmsb_legacy_9_v3',cs.account_id,cs.id,'v3','v',30,'active','{"title":"Community First","description":"From garage nights to poker runs, we''re building connections that matter. Real people, real stories, real freedom."}','$.content.v3','{"legacy_source":"r2-section-content","legacy_r2_key":"cms/pages/home/draft/values.json","family":"v","migration":"cms-data-family-20261007"}' FROM cms_page_sections cs WHERE cs.legacy_section_id=9 AND NOT EXISTS (SELECT 1 FROM cms_section_blocks cb WHERE cb.section_id=cs.id AND cb.block_key='v3');
