-- Generated by scripts/sync-agentsam-skills.mjs

INSERT OR REPLACE INTO agentsam_skill (
  id, slug, name, description, file_path, scope, slash_trigger,
  tags_json, globs_json, task_types_json, metadata_json,
  retrieval_strategy, sort_order, version, is_active, updated_at
) VALUES (
  'skill_stripe_best_practices',
  'stripe-best-practices',
  'stripe-best-practices',
  '',
  'agentsam/skills/stripe-best-practices/SKILL.md',
  'stripe',
  'stripe-best-practices',
  '["stripe_best_practices","stripe","payments","checkout","webhooks"]',
  '[]',
  '["stripe","payments","commerce"]',
  '{"r2_bucket":"fuelnfreetime","r2_skill_key":"agentsam/skills/stripe-best-practices/SKILL.md","source":".cursor/skills"}',
  'r2',
  10,
  1,
  1,
  datetime('now')
);

DELETE FROM agentsam_skill_file WHERE skill_id = 'skill_stripe_best_practices';
INSERT INTO agentsam_skill_file (skill_id, file_path, role, sort_order)
VALUES ('skill_stripe_best_practices', 'agentsam/skills/stripe-best-practices/references/billing.md', 'reference', 0);
INSERT INTO agentsam_skill_file (skill_id, file_path, role, sort_order)
VALUES ('skill_stripe_best_practices', 'agentsam/skills/stripe-best-practices/references/connect.md', 'reference', 1);
INSERT INTO agentsam_skill_file (skill_id, file_path, role, sort_order)
VALUES ('skill_stripe_best_practices', 'agentsam/skills/stripe-best-practices/references/payments.md', 'reference', 2);
INSERT INTO agentsam_skill_file (skill_id, file_path, role, sort_order)
VALUES ('skill_stripe_best_practices', 'agentsam/skills/stripe-best-practices/references/security.md', 'reference', 3);
INSERT INTO agentsam_skill_file (skill_id, file_path, role, sort_order)
VALUES ('skill_stripe_best_practices', 'agentsam/skills/stripe-best-practices/references/tax.md', 'reference', 4);
INSERT INTO agentsam_skill_file (skill_id, file_path, role, sort_order)
VALUES ('skill_stripe_best_practices', 'agentsam/skills/stripe-best-practices/references/treasury.md', 'reference', 5);

INSERT OR REPLACE INTO agentsam_skill (
  id, slug, name, description, file_path, scope, slash_trigger,
  tags_json, globs_json, task_types_json, metadata_json,
  retrieval_strategy, sort_order, version, is_active, updated_at
) VALUES (
  'skill_stripe_directory',
  'stripe-directory',
  'stripe-directory',
  '',
  'agentsam/skills/stripe-directory/SKILL.md',
  'stripe',
  'stripe-directory',
  '["stripe_directory","stripe","payments","checkout","webhooks"]',
  '[]',
  '["stripe","payments","commerce"]',
  '{"r2_bucket":"fuelnfreetime","r2_skill_key":"agentsam/skills/stripe-directory/SKILL.md","source":".cursor/skills"}',
  'r2',
  10,
  1,
  1,
  datetime('now')
);

DELETE FROM agentsam_skill_file WHERE skill_id = 'skill_stripe_directory';

INSERT OR REPLACE INTO agentsam_skill (
  id, slug, name, description, file_path, scope, slash_trigger,
  tags_json, globs_json, task_types_json, metadata_json,
  retrieval_strategy, sort_order, version, is_active, updated_at
) VALUES (
  'skill_stripe_projects',
  'stripe-projects',
  'stripe-projects',
  '>',
  'agentsam/skills/stripe-projects/SKILL.md',
  'stripe',
  'stripe-projects',
  '["stripe_projects","stripe","payments","checkout","webhooks"]',
  '[]',
  '["stripe","payments","commerce"]',
  '{"r2_bucket":"fuelnfreetime","r2_skill_key":"agentsam/skills/stripe-projects/SKILL.md","source":".cursor/skills"}',
  'r2',
  10,
  1,
  1,
  datetime('now')
);

DELETE FROM agentsam_skill_file WHERE skill_id = 'skill_stripe_projects';

INSERT OR REPLACE INTO agentsam_skill (
  id, slug, name, description, file_path, scope, slash_trigger,
  tags_json, globs_json, task_types_json, metadata_json,
  retrieval_strategy, sort_order, version, is_active, updated_at
) VALUES (
  'skill_upgrade_stripe',
  'upgrade-stripe',
  'upgrade-stripe',
  'Guide for upgrading Stripe API versions and SDKs',
  'agentsam/skills/upgrade-stripe/SKILL.md',
  'stripe',
  'upgrade-stripe',
  '["upgrade_stripe","stripe","payments","checkout","webhooks"]',
  '[]',
  '["stripe","payments","commerce"]',
  '{"r2_bucket":"fuelnfreetime","r2_skill_key":"agentsam/skills/upgrade-stripe/SKILL.md","source":".cursor/skills"}',
  'r2',
  10,
  1,
  1,
  datetime('now')
);

DELETE FROM agentsam_skill_file WHERE skill_id = 'skill_upgrade_stripe';

INSERT OR REPLACE INTO agentsam_skill (
  id, slug, name, description, file_path, scope, slash_trigger,
  tags_json, globs_json, task_types_json, metadata_json,
  retrieval_strategy, sort_order, version, is_active, updated_at
) VALUES (
  'skill_fnf_commerce_runtime',
  'fnf-commerce-runtime',
  'FNF commerce runtime contract',
  'Fuel & Free Time product, inventory, cart, checkout, and order rules from RUNTIME-CONTRACTS-COMMERCE.md.',
  'agentsam/skills/fnf-commerce-runtime/SKILL.md',
  'commerce',
  'commerce',
  '["commerce","products","inventory","orders","checkout"]',
  '["docs/RUNTIME-CONTRACTS-COMMERCE.md","src/store/**","src/admin/api.js"]',
  '["commerce","products","inventory","orders"]',
  '{"r2_bucket":"fuelnfreetime","r2_skill_key":"agentsam/skills/fnf-commerce-runtime/SKILL.md","source":"docs"}',
  'r2',
  5,
  1,
  1,
  datetime('now')
);

INSERT OR REPLACE INTO agentsam_skill (
  id, slug, name, description, file_path, scope, slash_trigger,
  tags_json, globs_json, task_types_json, metadata_json,
  retrieval_strategy, sort_order, version, is_active, updated_at
) VALUES (
  'skill_fnf_stripe_runtime',
  'fnf-stripe-runtime',
  'FNF Stripe implementation checklist',
  'Ordered Stripe Checkout tasks and inventory rules for Fuel & Free Time.',
  'agentsam/skills/fnf-stripe-runtime/SKILL.md',
  'stripe',
  'stripe',
  '["stripe","checkout","webhooks","payments"]',
  '["docs/RUNTIME-CONTRACTS-STRIPE.md",".cursor/skills/stripe-best-practices/**"]',
  '["stripe","payments","commerce"]',
  '{"r2_bucket":"fuelnfreetime","r2_skill_key":"agentsam/skills/fnf-stripe-runtime/SKILL.md","source":"docs"}',
  'r2',
  6,
  1,
  1,
  datetime('now')
);
