INSERT OR REPLACE INTO agentsam_ai (
  id, tenant_id, workspace_id, provider, model_id, display_name,
  description, task_type, lane, status, priority,
  is_default, is_fallback,
  supports_json, supports_tools, supports_vision, supports_streaming,
  context_window_tokens, max_output_tokens,
  quality_score, speed_score, cost_tier,
  workflow_keys_json, routing_keywords_json, capabilities_json,
  request_defaults_json, notes
) VALUES
('fnf_kimi_k2_chat','tenant_fuelnfreetime','ws_fuelnfreetime',
 'workers_ai','@cf/moonshotai/kimi-k2.6','Kimi K2.6 (Primary)',
 'Primary chat via fuelnfreetime-agentsam AI Gateway.',
 'text_generation','standard','active',1,1,0,
 1,0,0,1,131072,8192,85,80,'low',
 '[]','["chat","help","store","order","product","content","brand","email"]','[]',
 '{"temperature":0.5,"max_tokens":1024}',
 'Primary via CF AI Gateway. Fallback: llama-3.3-70b.'),

('fnf_llama33_fallback','tenant_fuelnfreetime','ws_fuelnfreetime',
 'workers_ai','@cf/meta/llama-3.3-70b-instruct','Llama 3.3 70B (Fallback)',
 'Fallback when primary unavailable.',
 'text_generation','fast','active',2,0,1,
 1,0,0,1,131072,8192,75,90,'low',
 '[]','[]','[]',
 '{"temperature":0.4,"max_tokens":1024}',
 'Emergency fallback, no gateway.'),

('fnf_flux_image','tenant_fuelnfreetime','ws_fuelnfreetime',
 'workers_ai','@cf/black-forest-labs/flux-1-schnell','Flux Schnell (Image Gen)',
 'Image gen for product shots, brand assets.',
 'image_generation','standard','active',1,1,0,
 0,0,0,0,0,0,80,85,'low',
 '[]','["image","photo","logo","generate","create"]','[]',
 '{"num_steps":4}',
 'Via gateway for observability.'),

('fnf_bge_embed','tenant_fuelnfreetime','ws_fuelnfreetime',
 'workers_ai','@cf/baai/bge-m3','BGE-M3 Embeddings',
 'Semantic search embeddings for store context.',
 'embedding','fast','active',1,1,0,
 0,0,0,0,8192,1024,90,95,'low',
 '[]','[]','[]',
 '{}',
 'Used by fnf-vectorize.js.');
