-- Generated from apps/ecommerce-cms-agentsam/fixtures/fnf-revise-site.json
-- Draft-only compatibility + canonical projection. Existing rows are never overwritten.
PRAGMA foreign_keys = ON;

INSERT INTO pages (slug,title,status) SELECT 'campaigns','Our Worlds','draft'
WHERE NOT EXISTS (SELECT 1 FROM pages WHERE slug='campaigns');

INSERT INTO cms_pages (id,account_id,legacy_page_id,slug,title,page_type,status,template_key,metadata_json)
SELECT 'cmsp_revise_campaigns',(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),p.id,p.slug,p.title,'standard','draft','revise','{"source":"fnf-revise-site","theme":"revise","path":"/campaigns/","description":"Different ways of moving. One reason for making the time.","import":"canonical-seed-v1"}'
FROM pages p WHERE p.slug='campaigns' AND NOT EXISTS (SELECT 1 FROM cms_pages cp WHERE cp.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND cp.slug=p.slug);

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'group','block','Group','basic','built_in','1','{"layout":{"type":"text"},"gap":{"type":"text"},"alignment":{"type":"text"}}','[]','{"canonical":true,"source":"cms-block-types"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='block' AND d.definition_key='group' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'heading','block','Heading','basic','built_in','1','{"text":{"type":"text"},"level":{"type":"number"}}','[]','{"canonical":true,"source":"cms-block-types"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='block' AND d.definition_key='heading' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'text','block','Text','basic','built_in','1','{"text":{"type":"textarea"}}','[]','{"canonical":true,"source":"cms-block-types"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='block' AND d.definition_key='text' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'image','block','Image','basic','built_in','1','{"asset_id":{"type":"media"},"alt":{"type":"text"},"link":{"type":"link"}}','[]','{"canonical":true,"source":"cms-block-types"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='block' AND d.definition_key='image' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'button','block','Button','basic','built_in','1','{"label":{"type":"text"},"href":{"type":"link"},"style":{"type":"text"}}','[]','{"canonical":true,"source":"cms-block-types"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='block' AND d.definition_key='button' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,max_blocks,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'editorial-grid','section','Revise · Dark Promo Grid','Revise','package','1','{"eyebrow":{"type":"text"},"heading":{"type":"text"},"anchor":{"type":"text"}}','["group"]',100,'{"theme":"revise","preset":"revise-atlas/dark-promo-grid","source_preset":"revise/dark-promo-grid","source_contract":"revise/site-section-v1"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='section' AND d.definition_key='editorial-grid' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,max_blocks,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'collection-split-media','section','Revise · Pinned Media Grid','Revise','package','1','{"eyebrow":{"type":"text"},"heading":{"type":"text"},"body":{"type":"textarea"},"mediaKey":{"type":"media"},"mediaAlt":{"type":"text"}}','["group"]',100,'{"theme":"revise","preset":"revise-atlas/pinned-media-grid","source_preset":"revise/pinned-media-grid","source_contract":"revise/site-section-v1"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='section' AND d.definition_key='collection-split-media' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,max_blocks,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'before-after','section','Revise · Before / After','Revise','package','1','{"eyebrow":{"type":"text"},"heading":{"type":"text"},"beforeKey":{"type":"media"},"afterKey":{"type":"media"},"beforeAlt":{"type":"text"},"afterAlt":{"type":"text"}}','[]',0,'{"theme":"revise","preset":"revise-atlas/before-after","source_preset":"revise/before-after","source_contract":"revise/site-section-v1"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='section' AND d.definition_key='before-after' AND d.version='1');

INSERT INTO cms_definitions (account_id,definition_key,kind,label,category,origin,version,settings_schema_json,allowed_blocks_json,max_blocks,metadata_json,status)
SELECT (SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1),'testimonials','section','Revise · Testimonials','Revise','package','1','{"eyebrow":{"type":"text"},"heading":{"type":"text"}}','["group"]',100,'{"theme":"revise","preset":"revise-atlas/testimonials","source_preset":"revise/testimonials","source_contract":"revise/site-section-v1"}','active'
WHERE NOT EXISTS (SELECT 1 FROM cms_definitions d WHERE d.account_id=(SELECT account_id FROM cms_pages ORDER BY created_at,id LIMIT 1) AND d.kind='section' AND d.definition_key='testimonials' AND d.version='1');

INSERT INTO page_sections (page_id,section_key,sort_order,content_json,status,content_version,content_hash)
SELECT p.id,'campaigns-dark-promo-grid-1',0,'{"eyebrow":"Fuel & Free Time / Three worlds","heading":"Three ways to make the time count.","anchor":"fnf-campaigns","campaigns-block-0":{"label":"Concept 01 · Performance","title":"High Octane","body":"For the late nights in the garage and the roads that make them worth it.","mediaKey":"fnf.high-octane","href":"/campaigns/#campaigns-pinned-media-grid-2"},"campaigns-block-1":{"label":"Concept 02 · Refined","title":"Masters","body":"Less noise. More purpose. Essentials that speak for themselves.","mediaKey":"fnf.masters","href":"/campaigns/#campaigns-before-after-3"},"campaigns-block-2":{"label":"Concept 03 · Editorial","title":"Project Stories","body":"The makers, machines, and places behind the things we love.","mediaKey":"fnf.build.heli.2","href":"/stories/"},"__editor":{"templateKey":"portable","themePreset":"revise-atlas/dark-promo-grid","sourcePreset":"revise/dark-promo-grid","sourceContract":"revise/site-section-v1","blocks":[{"id":"campaigns-block-0","templateKey":"item","enabled":true},{"id":"campaigns-block-1","templateKey":"item","enabled":true},{"id":"campaigns-block-2","templateKey":"item","enabled":true}],"media":{"fnf.high-octane":"/media/archive/shopify-import/graphics/high_octane.jpg","fnf.masters":"/media/themes/revise/campaigns/masters.webp","fnf.build.heli.2":"/media/uploads/staging/images/preview/img-8568.webp"}}}','draft',1,'f93197ac42cfa6418ce6dcd40b984d15a87b4d0c799c5a8f3ee657ee72ad204f' FROM pages p WHERE p.slug='campaigns' AND NOT EXISTS (SELECT 1 FROM page_sections ps WHERE ps.page_id=p.id AND ps.section_key='campaigns-dark-promo-grid-1');

INSERT INTO cms_page_sections (id,account_id,page_id,legacy_section_id,section_key,section_type,sort_order,status,inline_content_json,content_version,content_hash,metadata_json)
SELECT 'cmss_revise_campaigns_dark_promo_grid_1',cp.account_id,cp.id,ps.id,ps.section_key,'editorial-grid',ps.sort_order,'draft',ps.content_json,1,ps.content_hash,'{"source_theme":"revise","source_preset":"revise/dark-promo-grid","donor_section_id":"campaigns-dark-promo-grid-1","canonical_blocks":true,"inline_projection":"reviseAtlas"}' FROM page_sections ps JOIN pages p ON p.id=ps.page_id JOIN cms_pages cp ON cp.legacy_page_id=p.id WHERE p.slug='campaigns' AND ps.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_page_sections s WHERE s.page_id=cp.id AND s.section_key=ps.section_key);

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0',s.account_id,s.id,NULL,'campaigns_block_0','group',0,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-0','{"source_theme":"revise","source_block_type":"item","source_data":{"label":"Concept 01 · Performance","title":"High Octane","body":"For the late nights in the garage and the roads that make them worth it.","mediaKey":"fnf.high-octane","href":"/campaigns/#campaigns-pinned-media-grid-2"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0_label',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0','campaigns_block_0_label','text',0,'active','{"text":"Concept 01 · Performance"}','$.blocks.campaigns-block-0.label','{"source_theme":"revise","source_field":"label"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_label');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0_title',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0','campaigns_block_0_title','heading',10,'active','{"text":"High Octane","level":3}','$.blocks.campaigns-block-0.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0_body',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0','campaigns_block_0_body','text',20,'active','{"text":"For the late nights in the garage and the roads that make them worth it."}','$.blocks.campaigns-block-0.body','{"source_theme":"revise","source_field":"body"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_body');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0','campaigns_block_0_mediakey','image',30,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='archive/shopify-import/graphics/high_octane.jpg' LIMIT 1),'alt','High Octane','link','/campaigns/#campaigns-pinned-media-grid-2'),'$.blocks.campaigns-block-0.mediaKey','{"source_theme":"revise","media_key":"fnf.high-octane","r2_key":"archive/shopify-import/graphics/high_octane.jpg"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0_href',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_0','campaigns_block_0_href','button',40,'active','{"label":"High Octane","href":"/campaigns/#campaigns-pinned-media-grid-2","style":"link"}','$.blocks.campaigns-block-0.href','{"source_theme":"revise","source_field":"href"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_href');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1',s.account_id,s.id,NULL,'campaigns_block_1','group',10,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-1','{"source_theme":"revise","source_block_type":"item","source_data":{"label":"Concept 02 · Refined","title":"Masters","body":"Less noise. More purpose. Essentials that speak for themselves.","mediaKey":"fnf.masters","href":"/campaigns/#campaigns-before-after-3"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1_label',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1','campaigns_block_1_label','text',0,'active','{"text":"Concept 02 · Refined"}','$.blocks.campaigns-block-1.label','{"source_theme":"revise","source_field":"label"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_label');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1_title',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1','campaigns_block_1_title','heading',10,'active','{"text":"Masters","level":3}','$.blocks.campaigns-block-1.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1_body',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1','campaigns_block_1_body','text',20,'active','{"text":"Less noise. More purpose. Essentials that speak for themselves."}','$.blocks.campaigns-block-1.body','{"source_theme":"revise","source_field":"body"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_body');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1','campaigns_block_1_mediakey','image',30,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='themes/revise/campaigns/masters.webp' LIMIT 1),'alt','Masters','link','/campaigns/#campaigns-before-after-3'),'$.blocks.campaigns-block-1.mediaKey','{"source_theme":"revise","media_key":"fnf.masters","r2_key":"themes/revise/campaigns/masters.webp"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1_href',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_1','campaigns_block_1_href','button',40,'active','{"label":"Masters","href":"/campaigns/#campaigns-before-after-3","style":"link"}','$.blocks.campaigns-block-1.href','{"source_theme":"revise","source_field":"href"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_href');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2',s.account_id,s.id,NULL,'campaigns_block_2','group',20,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-2','{"source_theme":"revise","source_block_type":"item","source_data":{"label":"Concept 03 · Editorial","title":"Project Stories","body":"The makers, machines, and places behind the things we love.","mediaKey":"fnf.build.heli.2","href":"/stories/"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2_label',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2','campaigns_block_2_label','text',0,'active','{"text":"Concept 03 · Editorial"}','$.blocks.campaigns-block-2.label','{"source_theme":"revise","source_field":"label"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_label');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2_title',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2','campaigns_block_2_title','heading',10,'active','{"text":"Project Stories","level":3}','$.blocks.campaigns-block-2.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2_body',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2','campaigns_block_2_body','text',20,'active','{"text":"The makers, machines, and places behind the things we love."}','$.blocks.campaigns-block-2.body','{"source_theme":"revise","source_field":"body"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_body');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2','campaigns_block_2_mediakey','image',30,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='uploads/staging/images/preview/img-8568.webp' LIMIT 1),'alt','Project Stories','link','/stories/'),'$.blocks.campaigns-block-2.mediaKey','{"source_theme":"revise","media_key":"fnf.build.heli.2","r2_key":"uploads/staging/images/preview/img-8568.webp"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2_href',s.account_id,s.id,'cmsb_revise_campaigns_dark_promo_grid_1_campaigns_block_2','campaigns_block_2_href','button',40,'active','{"label":"Project Stories","href":"/stories/","style":"link"}','$.blocks.campaigns-block-2.href','{"source_theme":"revise","source_field":"href"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_href');

INSERT INTO cms_revisions (id,account_id,entity_type,entity_id,revision_number,revision_kind,content_hash,snapshot_json,metadata_json)
SELECT 'cmsr_revise_campaigns_dark_promo_grid_1_v1',s.account_id,'section',s.id,1,'imported',s.content_hash,s.inline_content_json,'{"source_theme":"revise","source_preset":"revise/dark-promo-grid","import":"canonical-seed-v1"}' FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-dark-promo-grid-1' AND NOT EXISTS (SELECT 1 FROM cms_revisions r WHERE r.entity_type='section' AND r.entity_id=s.id AND r.revision_number=1 AND r.revision_kind='imported');

INSERT INTO page_sections (page_id,section_key,sort_order,content_json,status,content_version,content_hash)
SELECT p.id,'campaigns-pinned-media-grid-2',10,'{"eyebrow":"Collection concept / existing brand direction","heading":"High Octane","body":"Performance-minded gear for garage nights, open roads, and redline living.","mediaKey":"fnf.high-octane","mediaAlt":"Fuel & Free Time High Octane action imagery","campaigns-block-0":{"title":"Heavyweight Tee","price":"Demo $32","mediaKey":"completeful.heavyweight-tee","badge":"Catalog"},"campaigns-block-1":{"title":"Bamboo Sunglasses","price":"Demo $24","mediaKey":"completeful.bamboo-sunglasses","badge":"Catalog"},"campaigns-block-2":{"title":"Stainless Tumbler","price":"Demo $28","mediaKey":"completeful.stainless-tumbler","badge":"Catalog"},"campaigns-block-3":{"title":"Luggage Tag","price":"Demo $16","mediaKey":"completeful.luggage-tag","badge":"Catalog"},"__editor":{"templateKey":"portable","themePreset":"revise-atlas/pinned-media-grid","sourcePreset":"revise/pinned-media-grid","sourceContract":"revise/site-section-v1","blocks":[{"id":"campaigns-block-0","templateKey":"item","enabled":true},{"id":"campaigns-block-1","templateKey":"item","enabled":true},{"id":"campaigns-block-2","templateKey":"item","enabled":true},{"id":"campaigns-block-3","templateKey":"item","enabled":true}],"media":{"fnf.high-octane":"/media/archive/shopify-import/graphics/high_octane.jpg","completeful.heavyweight-tee":"/media/themes/revise/campaigns/heavyweight-tee.png","completeful.bamboo-sunglasses":"/media/themes/revise/campaigns/bamboo-sunglasses.jpg","completeful.stainless-tumbler":"/media/themes/revise/campaigns/stainless-tumbler.png","completeful.luggage-tag":"/media/themes/revise/campaigns/luggage-tag.jpg"}}}','draft',1,'48907ba64f6117765e99d32f66ce6359dbc68bd240eee45dec683520829b6e08' FROM pages p WHERE p.slug='campaigns' AND NOT EXISTS (SELECT 1 FROM page_sections ps WHERE ps.page_id=p.id AND ps.section_key='campaigns-pinned-media-grid-2');

INSERT INTO cms_page_sections (id,account_id,page_id,legacy_section_id,section_key,section_type,sort_order,status,inline_content_json,content_version,content_hash,metadata_json)
SELECT 'cmss_revise_campaigns_pinned_media_grid_2',cp.account_id,cp.id,ps.id,ps.section_key,'collection-split-media',ps.sort_order,'draft',ps.content_json,1,ps.content_hash,'{"source_theme":"revise","source_preset":"revise/pinned-media-grid","donor_section_id":"campaigns-pinned-media-grid-2","canonical_blocks":true,"inline_projection":"reviseAtlas"}' FROM page_sections ps JOIN pages p ON p.id=ps.page_id JOIN cms_pages cp ON cp.legacy_page_id=p.id WHERE p.slug='campaigns' AND ps.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_page_sections s WHERE s.page_id=cp.id AND s.section_key=ps.section_key);

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0',s.account_id,s.id,NULL,'campaigns_block_0','group',0,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-0','{"source_theme":"revise","source_block_type":"item","source_data":{"title":"Heavyweight Tee","price":"Demo $32","mediaKey":"completeful.heavyweight-tee","badge":"Catalog"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0_title',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0','campaigns_block_0_title','heading',0,'active','{"text":"Heavyweight Tee","level":3}','$.blocks.campaigns-block-0.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0_price',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0','campaigns_block_0_price','text',10,'active','{"text":"Demo $32"}','$.blocks.campaigns-block-0.price','{"source_theme":"revise","source_field":"price"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_price');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0','campaigns_block_0_mediakey','image',20,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='themes/revise/campaigns/heavyweight-tee.png' LIMIT 1),'alt','Heavyweight Tee','link',''),'$.blocks.campaigns-block-0.mediaKey','{"source_theme":"revise","media_key":"completeful.heavyweight-tee","r2_key":"themes/revise/campaigns/heavyweight-tee.png"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0_badge',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_0','campaigns_block_0_badge','text',30,'active','{"text":"Catalog"}','$.blocks.campaigns-block-0.badge','{"source_theme":"revise","source_field":"badge"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_badge');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1',s.account_id,s.id,NULL,'campaigns_block_1','group',10,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-1','{"source_theme":"revise","source_block_type":"item","source_data":{"title":"Bamboo Sunglasses","price":"Demo $24","mediaKey":"completeful.bamboo-sunglasses","badge":"Catalog"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1_title',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1','campaigns_block_1_title','heading',0,'active','{"text":"Bamboo Sunglasses","level":3}','$.blocks.campaigns-block-1.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1_price',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1','campaigns_block_1_price','text',10,'active','{"text":"Demo $24"}','$.blocks.campaigns-block-1.price','{"source_theme":"revise","source_field":"price"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_price');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1','campaigns_block_1_mediakey','image',20,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='themes/revise/campaigns/bamboo-sunglasses.jpg' LIMIT 1),'alt','Bamboo Sunglasses','link',''),'$.blocks.campaigns-block-1.mediaKey','{"source_theme":"revise","media_key":"completeful.bamboo-sunglasses","r2_key":"themes/revise/campaigns/bamboo-sunglasses.jpg"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1_badge',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_1','campaigns_block_1_badge','text',30,'active','{"text":"Catalog"}','$.blocks.campaigns-block-1.badge','{"source_theme":"revise","source_field":"badge"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_badge');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2',s.account_id,s.id,NULL,'campaigns_block_2','group',20,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-2','{"source_theme":"revise","source_block_type":"item","source_data":{"title":"Stainless Tumbler","price":"Demo $28","mediaKey":"completeful.stainless-tumbler","badge":"Catalog"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2_title',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2','campaigns_block_2_title','heading',0,'active','{"text":"Stainless Tumbler","level":3}','$.blocks.campaigns-block-2.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2_price',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2','campaigns_block_2_price','text',10,'active','{"text":"Demo $28"}','$.blocks.campaigns-block-2.price','{"source_theme":"revise","source_field":"price"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_price');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2','campaigns_block_2_mediakey','image',20,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='themes/revise/campaigns/stainless-tumbler.png' LIMIT 1),'alt','Stainless Tumbler','link',''),'$.blocks.campaigns-block-2.mediaKey','{"source_theme":"revise","media_key":"completeful.stainless-tumbler","r2_key":"themes/revise/campaigns/stainless-tumbler.png"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2_badge',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_2','campaigns_block_2_badge','text',30,'active','{"text":"Catalog"}','$.blocks.campaigns-block-2.badge','{"source_theme":"revise","source_field":"badge"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_badge');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3',s.account_id,s.id,NULL,'campaigns_block_3','group',30,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-3','{"source_theme":"revise","source_block_type":"item","source_data":{"title":"Luggage Tag","price":"Demo $16","mediaKey":"completeful.luggage-tag","badge":"Catalog"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_3');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3_title',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3','campaigns_block_3_title','heading',0,'active','{"text":"Luggage Tag","level":3}','$.blocks.campaigns-block-3.title','{"source_theme":"revise","source_field":"title"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_3_title');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3_price',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3','campaigns_block_3_price','text',10,'active','{"text":"Demo $16"}','$.blocks.campaigns-block-3.price','{"source_theme":"revise","source_field":"price"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_3_price');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3_mediakey',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3','campaigns_block_3_mediakey','image',20,'active',json_object('asset_id',(SELECT id FROM media_assets WHERE r2_key='themes/revise/campaigns/luggage-tag.jpg' LIMIT 1),'alt','Luggage Tag','link',''),'$.blocks.campaigns-block-3.mediaKey','{"source_theme":"revise","media_key":"completeful.luggage-tag","r2_key":"themes/revise/campaigns/luggage-tag.jpg"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_3_mediakey');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3_badge',s.account_id,s.id,'cmsb_revise_campaigns_pinned_media_grid_2_campaigns_block_3','campaigns_block_3_badge','text',30,'active','{"text":"Catalog"}','$.blocks.campaigns-block-3.badge','{"source_theme":"revise","source_field":"badge"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_3_badge');

INSERT INTO cms_revisions (id,account_id,entity_type,entity_id,revision_number,revision_kind,content_hash,snapshot_json,metadata_json)
SELECT 'cmsr_revise_campaigns_pinned_media_grid_2_v1',s.account_id,'section',s.id,1,'imported',s.content_hash,s.inline_content_json,'{"source_theme":"revise","source_preset":"revise/pinned-media-grid","import":"canonical-seed-v1"}' FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-pinned-media-grid-2' AND NOT EXISTS (SELECT 1 FROM cms_revisions r WHERE r.entity_type='section' AND r.entity_id=s.id AND r.revision_number=1 AND r.revision_kind='imported');

INSERT INTO page_sections (page_id,section_key,sort_order,content_json,status,content_version,content_hash)
SELECT p.id,'campaigns-before-after-3',20,'{"eyebrow":"Brand tension","heading":"Fuel on one side. Free time on the other.","beforeKey":"fnf.masters","afterKey":"fnf.essentials","beforeAlt":"Garage and automotive lifestyle","afterAlt":"Lakeside free-time lifestyle","__editor":{"templateKey":"portable","themePreset":"revise-atlas/before-after","sourcePreset":"revise/before-after","sourceContract":"revise/site-section-v1","blocks":[],"media":{"fnf.masters":"/media/themes/revise/campaigns/masters.webp","fnf.essentials":"/media/themes/revise/campaigns/essentials.webp"}}}','draft',1,'0558eda423a10f98fdd2bdf67b85e8604c5b87f1a55dde6d57eb3ac918425485' FROM pages p WHERE p.slug='campaigns' AND NOT EXISTS (SELECT 1 FROM page_sections ps WHERE ps.page_id=p.id AND ps.section_key='campaigns-before-after-3');

INSERT INTO cms_page_sections (id,account_id,page_id,legacy_section_id,section_key,section_type,sort_order,status,inline_content_json,content_version,content_hash,metadata_json)
SELECT 'cmss_revise_campaigns_before_after_3',cp.account_id,cp.id,ps.id,ps.section_key,'before-after',ps.sort_order,'draft',ps.content_json,1,ps.content_hash,'{"source_theme":"revise","source_preset":"revise/before-after","donor_section_id":"campaigns-before-after-3","canonical_blocks":true,"inline_projection":"reviseAtlas"}' FROM page_sections ps JOIN pages p ON p.id=ps.page_id JOIN cms_pages cp ON cp.legacy_page_id=p.id WHERE p.slug='campaigns' AND ps.section_key='campaigns-before-after-3' AND NOT EXISTS (SELECT 1 FROM cms_page_sections s WHERE s.page_id=cp.id AND s.section_key=ps.section_key);

INSERT INTO cms_revisions (id,account_id,entity_type,entity_id,revision_number,revision_kind,content_hash,snapshot_json,metadata_json)
SELECT 'cmsr_revise_campaigns_before_after_3_v1',s.account_id,'section',s.id,1,'imported',s.content_hash,s.inline_content_json,'{"source_theme":"revise","source_preset":"revise/before-after","import":"canonical-seed-v1"}' FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-before-after-3' AND NOT EXISTS (SELECT 1 FROM cms_revisions r WHERE r.entity_type='section' AND r.entity_id=s.id AND r.revision_number=1 AND r.revision_kind='imported');

INSERT INTO page_sections (page_id,section_key,sort_order,content_json,status,content_version,content_hash)
SELECT p.id,'campaigns-testimonials-4',30,'{"eyebrow":"Existing brand language","heading":"Words we live by.","campaigns-block-0":{"quote":"Time isn''t money. Time is everything money can''t buy back.","by":"About / brand story"},"campaigns-block-1":{"quote":"Every mile has a story. Every hour is earned.","by":"Community"},"campaigns-block-2":{"quote":"Real people, real stories, real freedom.","by":"Home / community value"},"__editor":{"templateKey":"portable","themePreset":"revise-atlas/testimonials","sourcePreset":"revise/testimonials","sourceContract":"revise/site-section-v1","blocks":[{"id":"campaigns-block-0","templateKey":"item","enabled":true},{"id":"campaigns-block-1","templateKey":"item","enabled":true},{"id":"campaigns-block-2","templateKey":"item","enabled":true}],"media":{}}}','draft',1,'038c138245ec305ddcc3d90adcf7725fb20602ac8fb06741a904818000f6e2cf' FROM pages p WHERE p.slug='campaigns' AND NOT EXISTS (SELECT 1 FROM page_sections ps WHERE ps.page_id=p.id AND ps.section_key='campaigns-testimonials-4');

INSERT INTO cms_page_sections (id,account_id,page_id,legacy_section_id,section_key,section_type,sort_order,status,inline_content_json,content_version,content_hash,metadata_json)
SELECT 'cmss_revise_campaigns_testimonials_4',cp.account_id,cp.id,ps.id,ps.section_key,'testimonials',ps.sort_order,'draft',ps.content_json,1,ps.content_hash,'{"source_theme":"revise","source_preset":"revise/testimonials","donor_section_id":"campaigns-testimonials-4","canonical_blocks":true,"inline_projection":"reviseAtlas"}' FROM page_sections ps JOIN pages p ON p.id=ps.page_id JOIN cms_pages cp ON cp.legacy_page_id=p.id WHERE p.slug='campaigns' AND ps.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_page_sections s WHERE s.page_id=cp.id AND s.section_key=ps.section_key);

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_0',s.account_id,s.id,NULL,'campaigns_block_0','group',0,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-0','{"source_theme":"revise","source_block_type":"item","source_data":{"quote":"Time isn''t money. Time is everything money can''t buy back.","by":"About / brand story"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_0_quote',s.account_id,s.id,'cmsb_revise_campaigns_testimonials_4_campaigns_block_0','campaigns_block_0_quote','text',0,'active','{"text":"Time isn''t money. Time is everything money can''t buy back."}','$.blocks.campaigns-block-0.quote','{"source_theme":"revise","source_field":"quote"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_quote');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_0_by',s.account_id,s.id,'cmsb_revise_campaigns_testimonials_4_campaigns_block_0','campaigns_block_0_by','text',10,'active','{"text":"About / brand story"}','$.blocks.campaigns-block-0.by','{"source_theme":"revise","source_field":"by"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_0_by');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_1',s.account_id,s.id,NULL,'campaigns_block_1','group',10,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-1','{"source_theme":"revise","source_block_type":"item","source_data":{"quote":"Every mile has a story. Every hour is earned.","by":"Community"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_1_quote',s.account_id,s.id,'cmsb_revise_campaigns_testimonials_4_campaigns_block_1','campaigns_block_1_quote','text',0,'active','{"text":"Every mile has a story. Every hour is earned."}','$.blocks.campaigns-block-1.quote','{"source_theme":"revise","source_field":"quote"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_quote');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_1_by',s.account_id,s.id,'cmsb_revise_campaigns_testimonials_4_campaigns_block_1','campaigns_block_1_by','text',10,'active','{"text":"Community"}','$.blocks.campaigns-block-1.by','{"source_theme":"revise","source_field":"by"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_1_by');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_2',s.account_id,s.id,NULL,'campaigns_block_2','group',20,'active','{"layout":"card","gap":"sm","alignment":"start"}','$.blocks.campaigns-block-2','{"source_theme":"revise","source_block_type":"item","source_data":{"quote":"Real people, real stories, real freedom.","by":"Home / community value"}}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_2_quote',s.account_id,s.id,'cmsb_revise_campaigns_testimonials_4_campaigns_block_2','campaigns_block_2_quote','text',0,'active','{"text":"Real people, real stories, real freedom."}','$.blocks.campaigns-block-2.quote','{"source_theme":"revise","source_field":"quote"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_quote');

INSERT INTO cms_section_blocks (id,account_id,section_id,parent_block_id,block_key,block_type,sort_order,status,content_json,source_path,metadata_json)
SELECT 'cmsb_revise_campaigns_testimonials_4_campaigns_block_2_by',s.account_id,s.id,'cmsb_revise_campaigns_testimonials_4_campaigns_block_2','campaigns_block_2_by','text',10,'active','{"text":"Home / community value"}','$.blocks.campaigns-block-2.by','{"source_theme":"revise","source_field":"by"}'
FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_section_blocks b WHERE b.section_id=s.id AND b.block_key='campaigns_block_2_by');

INSERT INTO cms_revisions (id,account_id,entity_type,entity_id,revision_number,revision_kind,content_hash,snapshot_json,metadata_json)
SELECT 'cmsr_revise_campaigns_testimonials_4_v1',s.account_id,'section',s.id,1,'imported',s.content_hash,s.inline_content_json,'{"source_theme":"revise","source_preset":"revise/testimonials","import":"canonical-seed-v1"}' FROM cms_page_sections s JOIN cms_pages p ON p.id=s.page_id WHERE p.slug='campaigns' AND s.section_key='campaigns-testimonials-4' AND NOT EXISTS (SELECT 1 FROM cms_revisions r WHERE r.entity_type='section' AND r.entity_id=s.id AND r.revision_number=1 AND r.revision_kind='imported');

INSERT INTO cms_revisions (id,account_id,entity_type,entity_id,revision_number,revision_kind,snapshot_json,metadata_json)
SELECT 'cmsr_revise_campaigns_v1',p.account_id,'page',p.id,1,'imported','{"slug":"campaigns","title":"Our Worlds","template_key":"revise","source_path":"/campaigns/"}','{"source_theme":"revise","import":"canonical-seed-v1"}' FROM cms_pages p WHERE p.slug='campaigns' AND NOT EXISTS (SELECT 1 FROM cms_revisions r WHERE r.entity_type='page' AND r.entity_id=p.id AND r.revision_number=1 AND r.revision_kind='imported');

