-- ctx_fuelnfreetime — IAM platform D1 (inneranimalmedia-business) client registry
-- Apply: npm run db:seed:ctx-fuelnfreetime:iam
-- Table already exists on IAM; INSERT OR REPLACE only.

INSERT OR REPLACE INTO agentsam_project_context (
  id,
  tenant_id,
  workspace_id,
  project_key,
  project_name,
  project_type,
  status,
  priority,
  description,
  goals,
  constraints,
  current_blockers,
  primary_tables,
  secondary_tables,
  workers_involved,
  r2_buckets_involved,
  domains_involved,
  mcp_services_involved,
  key_files,
  related_routes,
  notes,
  created_by,
  started_at,
  created_at,
  updated_at
) VALUES (
  'ctx_fuelnfreetime',
  'tenant_sam_primeaux',
  'ws_inneranimalmedia',
  'fuelnfreetime',
  'Fuel & Free Time — client worker (IAM registry)',
  'client_worker',
  'active',
  85,
  'Client worker `fuelnfreetime` for Fuel & Free Time apparel/store (Justin Molaison, Lafayette LA). GitHub: github.com/SamPrimeaux/fuelnfreetime. Production: fuelnfreetime.com. Worker D1: fuelnfreetime (9fd6ff92-e407-4b51-8b01-3c93f3845bb2) — NOT inneranimalmedia-business. Client tenant: tenant_fuelnfreetime / ws_fuelnfreetime. R2 bucket fuelnfreetime (/media/*, agentsam/skills/*). KV CMS_CACHE. DO CMS_EDITOR. Collaborators: Connor McNeely (repo + CF). Commerce: D1 products/variants/inventory, cart, checkout v1 without Stripe. CMS: R2-backed sections + KV publish. Agent Sam skills synced to client R2+D1. IAM docs in client repo: AGENTS.md, RUNTIME-CONTRACTS-*.md. Do NOT patch client runtime from ctx_inneranimalmedia — use this row or client repo SSOT.',
  '["P0: Stripe integration on client worker (see client docs/RUNTIME-CONTRACTS-STRIPE.md)","P1: Client order email via Resend","P1: Ingest client repo into IAM RAG (optional client_project_semantic_search lane)","P2: Webhook registry awh_stripe_checkout activation on client worker"]',
  '["Client worker/repo separate from IAM platform — deploy from /Users/samprimeaux/fuelnfreetime only","Client D1 fuelnfreetime is runtime SoT — IAM row is compass/registry only","Never apply inneranimalmedia migrations to client D1","Connor: read client AGENTS.md + npm run agentsam:skills:sync on client repo","Stripe skills vendored at client .cursor/skills/stripe-best-practices/"]',
  '["Stripe not wired on client worker","Client ctx row on worker D1 must stay in sync with this IAM registry row","No IAM Vectorize ingest of client repo yet (optional)"]',
  'products,product_variants,orders,order_items,pages,page_sections,agentsam_skill,agentsam_webhooks',
  'agentsam_skill_file,agentsam_hook,agentsam_webhook_events,agentsam_workflows,agentsam_mcp_workflows,media_assets,store_settings',
  'fuelnfreetime',
  'fuelnfreetime',
  'fuelnfreetime.com,www.fuelnfreetime.com,fuelnfreetime.meauxbility.workers.dev',
  'https://mcp.stripe.com (planned for Connor Stripe sprint)',
  'github.com/SamPrimeaux/fuelnfreetime/AGENTS.md,github.com/SamPrimeaux/fuelnfreetime/docs/RUNTIME-CONTRACTS-STRIPE.md,github.com/SamPrimeaux/fuelnfreetime/docs/AGENTSAM-SKILLS.md',
  'https://fuelnfreetime.com/api/store/*,https://fuelnfreetime.com/api/admin/*,https://fuelnfreetime.com/admin/login',
  'IAM canonical client registry row for fuelnfreetime. Worker-local mirror: ctx_fuelnfreetime on D1 fuelnfreetime with tenant_fuelnfreetime. Pairs with ctx_inneranimalmedia (platform master).',
  'au_871d920d1233cbd1',
  unixepoch(),
  COALESCE((SELECT created_at FROM agentsam_project_context WHERE id = 'ctx_fuelnfreetime'), unixepoch()),
  unixepoch()
);
