-- GENERATED by apps/ecommerce-cms-agentsam/bin/repository-contracts.mjs
-- Source: apps/ecommerce-cms-agentsam/repository.contracts.json
INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
) VALUES
('rct_788ed30c783541ce', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'runtime.agent-sam', '1.0.0', 'runtime', 'AgentSam runtime contract', 'Repository-level AgentSam runtime guidance.', 'AGENTSAM.md', '940496411bd499bb5575fe2b3441b3092e95eea997a66b1bafbb0db2a511e211', 'active', '{"family":"ecommerce-cms-agentsam","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_b877060ef5dca29f', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'application.ecommerce-cms-agentsam', '1.0.0', 'package', 'Ecommerce + CMS application contract', 'Canonical reusable Ecommerce application contract: core admin surface plus bundled Apps.', 'apps/ecommerce-cms-agentsam/agentsam.app.json', '564e18b6cca5763f71553b34bf5d2d582378dd2e3388d7cce62eaffed1290d51', 'active', '{"classification":"application","apps_registry":"apps/ecommerce-cms-agentsam/apps/registry.json","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_90b12bb5ef3ffdfd', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'surface.admin', '1.0.0', 'runtime', 'Ecommerce admin surface', 'Core admin shell/surface contract; not an optional feature.', 'apps/ecommerce-cms-agentsam/frontend/admin.surface.json', 'ea421c2ecde876e067db2714537b532d5132d7351d672ac9d0fc5e18d3c6448d', 'active', '{"route_authority":"apps/ecommerce-cms-agentsam/backend/lib/route-manifest.js","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_ab22b8ef8ca4de3f', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'app.product-studio', '1.0.0', 'package', 'Product Studio App', 'Bundled commerce Product Studio App contract.', 'apps/ecommerce-cms-agentsam/apps/product-studio/agentsam.app.json', 'bec3505bde00d306ded43cd94b716e87156f3848df2fb2521cc0640aa56d1e7c', 'active', '{"app_id":"product-studio","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_06e61c98e43bae1c', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'app.growth', '1.0.0', 'package', 'Growth App', 'Bundled Growth/marketing App contract.', 'apps/ecommerce-cms-agentsam/apps/growth/agentsam.app.json', '73e7047599e1e54d0f54b16a237489c06ee8e93de21a574a8c607ab19d2f3edd', 'active', '{"app_id":"growth","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_3836e0652821d0b9', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'app.completeful', '1.0.0', 'package', 'Completeful App', 'Bundled Completeful provider App contract.', 'apps/ecommerce-cms-agentsam/apps/completeful/agentsam.app.json', '568d3425afc9fdc326fd940810653f15917d329cf153cfd62783b6b71c30baf2', 'active', '{"app_id":"completeful","plugin_key":"completeful","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_88b98a67db6126d7', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'app.resend', '1.0.0', 'package', 'Resend Email App', 'Bundled Email/Resend provider App contract with mailbox-scoped authorization.', 'apps/ecommerce-cms-agentsam/apps/resend/agentsam.app.json', '86b1b720ff9f7067e5f539711a7bf4ed67006c02d50837e047f9b23739ee1018', 'active', '{"app_id":"resend","plugin_key":"resend","mailbox_authority":"mail_mailboxes","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_86543ac99cbd729f', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'schema.agentsam-tools', '2.0.0', 'schema', 'AgentSam tool authority', 'agentsam_tools owns tool capability, App, operation and resource-scope metadata; agentsam_tool_capabilities is compatibility-only.', 'db/migrate-agentsam-tools-authority-20261007.sql', 'a92c153f29a33c3d1e6396f6427636eb8da06ef9fb9e9d4cb177dcc8df205748', 'active', '{"tool_table":"agentsam_tools","capability_dictionary":"agentsam_capabilities","compatibility_view":"agentsam_tool_capabilities","hash_algorithm":"sha256"}', unixepoch(), unixepoch()),
('rct_ea1b6edb055f49f5', 'acct_fuelnfreetime', 'github:samprimeaux/fuelnfreetime', 'package.completeful', '1.0.0', 'package', 'Completeful package compatibility alias', 'Legacy contract key retained for compatibility; canonical ownership moved to app.completeful.', 'apps/ecommerce-cms-agentsam/apps/completeful/agentsam.app.json', '568d3425afc9fdc326fd940810653f15917d329cf153cfd62783b6b71c30baf2', 'deprecated', '{"canonical_contract":"app.completeful","plugin_key":"completeful","family":"ecommerce-cms-agentsam","hash_algorithm":"sha256"}', unixepoch(), unixepoch())
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();
