-- GENERATED by apps/ecommerce-cms-agentsam/bin/repository-contracts.mjs
-- Source: apps/ecommerce-cms-agentsam/repository.contracts.json
-- account_id is bound from code_repositories; an unregistered repository seeds nothing.
INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_788ed30c783541ce', r.account_id, r.id, 'runtime.agent-sam', '1.0.0', 'runtime', 'AgentSam runtime contract', 'Repository-level AgentSam runtime guidance.', 'AGENTSAM.md', '940496411bd499bb5575fe2b3441b3092e95eea997a66b1bafbb0db2a511e211', 'active', '{"family":"ecommerce-cms-agentsam","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_b877060ef5dca29f', r.account_id, r.id, 'application.ecommerce-cms-agentsam', '1.0.0', 'package', 'Ecommerce + CMS application contract', 'Canonical reusable Ecommerce application contract: core admin surface plus bundled Apps.', 'apps/ecommerce-cms-agentsam/agentsam.app.json', 'b3e1ec2c4b8ea0fb1e5bd4205edddcb7734b60fa2b86bda0bcdd1c7ffc10a77f', 'active', '{"classification":"application","apps_registry":"apps/ecommerce-cms-agentsam/apps/registry.json","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_90b12bb5ef3ffdfd', r.account_id, r.id, 'surface.admin', '1.0.0', 'runtime', 'Ecommerce admin surface', 'Core admin shell/surface contract; not an optional feature.', 'apps/ecommerce-cms-agentsam/frontend/admin.surface.json', 'ea421c2ecde876e067db2714537b532d5132d7351d672ac9d0fc5e18d3c6448d', 'active', '{"route_authority":"apps/ecommerce-cms-agentsam/backend/lib/route-manifest.js","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_ab22b8ef8ca4de3f', r.account_id, r.id, 'app.product-studio', '1.0.0', 'package', 'Product Studio App', 'Bundled commerce Product Studio App contract.', 'apps/ecommerce-cms-agentsam/apps/product-studio/agentsam.app.json', 'bec3505bde00d306ded43cd94b716e87156f3848df2fb2521cc0640aa56d1e7c', 'active', '{"app_id":"product-studio","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_06e61c98e43bae1c', r.account_id, r.id, 'app.growth', '1.0.0', 'package', 'Growth App', 'Bundled Growth/marketing App contract.', 'apps/ecommerce-cms-agentsam/apps/growth/agentsam.app.json', '73e7047599e1e54d0f54b16a237489c06ee8e93de21a574a8c607ab19d2f3edd', 'active', '{"app_id":"growth","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_3836e0652821d0b9', r.account_id, r.id, 'app.completeful', '1.0.0', 'package', 'Completeful App', 'Bundled Completeful provider App contract.', 'apps/ecommerce-cms-agentsam/apps/completeful/agentsam.app.json', '568d3425afc9fdc326fd940810653f15917d329cf153cfd62783b6b71c30baf2', 'active', '{"app_id":"completeful","plugin_key":"completeful","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_88b98a67db6126d7', r.account_id, r.id, 'app.resend', '1.0.0', 'package', 'Resend Email App', 'Bundled Email/Resend provider App contract with mailbox-scoped authorization.', 'apps/ecommerce-cms-agentsam/apps/resend/agentsam.app.json', '86b1b720ff9f7067e5f539711a7bf4ed67006c02d50837e047f9b23739ee1018', 'active', '{"app_id":"resend","plugin_key":"resend","mailbox_authority":"mail_mailboxes","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_86543ac99cbd729f', r.account_id, r.id, 'schema.agentsam-tools', '2.0.0', 'schema', 'AgentSam tool authority', 'agentsam_tools owns tool capability, App, operation and resource-scope metadata; agentsam_tool_capabilities is compatibility-only.', 'db/migrate-agentsam-tools-authority-20261007.sql', 'a92c153f29a33c3d1e6396f6427636eb8da06ef9fb9e9d4cb177dcc8df205748', 'active', '{"tool_table":"agentsam_tools","capability_dictionary":"agentsam_capabilities","compatibility_view":"agentsam_tool_capabilities","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_ea1b6edb055f49f5', r.account_id, r.id, 'package.completeful', '1.0.0', 'package', 'Completeful package compatibility alias', 'Legacy contract key retained for compatibility; canonical ownership moved to app.completeful.', 'apps/ecommerce-cms-agentsam/apps/completeful/agentsam.app.json', '568d3425afc9fdc326fd940810653f15917d329cf153cfd62783b6b71c30baf2', 'deprecated', '{"canonical_contract":"app.completeful","plugin_key":"completeful","family":"ecommerce-cms-agentsam","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_3500090f84d8853f', r.account_id, r.id, 'schema.cms-data-family', '1.0.0', 'schema', 'CMS normalized data family', 'Parallel normalized CMS page, section, block, revision and global tables with legacy provenance; renderer/editor authority remains on pages/page_sections during migration.', 'db/migrate-cms-data-family-20261007.sql', '396d08196d946e730ab4be61e8a2320d553a2c22a28e0b6f2ee4e92f77cedda1', 'active', '{"tables":["cms_pages","cms_page_sections","cms_section_blocks","cms_revisions","cms_globals"],"legacy_authority":["pages","page_sections"],"migration_mode":"parallel-backfill","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();

INSERT INTO agentsam_repository_contracts (
  id, account_id, repository_id, contract_key, contract_version, contract_type,
  name, description, manifest_path, contract_hash, status, metadata_json,
  created_at, updated_at
)
SELECT 'rct_b296c0210a387ed7', r.account_id, r.id, 'schema.cms-artifacts-block-system', '1.0.0', 'schema', 'CMS artifact + nested block system', 'Canonical D1/SQLite CMS schema with artifact-backed custom blocks, nested groups, provider-neutral artifact provenance and block integrity guards.', 'db/schema/cms.sql', 'c5197d54540195b2119fd57077da4305f406eb43fb41ad88e4945d15f33b1577', 'active', '{"tables":["cms_artifacts","cms_section_blocks"],"canonical_schema":"db/schema/cms.sql","migration":"db/migrate-cms-artifacts-block-tree-20261007.sql","integrity_migration":"db/migrate-cms-block-integrity-20261007.sql","block_registry":"apps/ecommerce-cms-agentsam/cms/block-types.json","hash_algorithm":"sha256"}', unixepoch(), unixepoch()
FROM code_repositories r WHERE r.id = 'github:samprimeaux/fuelnfreetime'
ON CONFLICT(repository_id,contract_key,contract_version) DO UPDATE SET
  account_id=excluded.account_id,
  contract_type=excluded.contract_type,
  name=excluded.name,
  description=excluded.description,
  manifest_path=excluded.manifest_path,
  contract_hash=excluded.contract_hash,
  status=excluded.status,
  metadata_json=excluded.metadata_json,
  updated_at=unixepoch();
