-- Bundled Ecommerce App tool registrations — 2026-10-07
-- Growth + Resend/Email use existing admin runtime paths; no duplicate business logic.

-- Resend is an installed provider App. Mailbox authorization remains D1 mail_mailboxes authority.
INSERT INTO agentsam_plugins (
  id, account_id, plugin_key, provider_key, installation_key, environment,
  plugin_kind, category, display_name, short_name, description,
  endpoint_url, transport, auth_type, secret_ref,
  capabilities_json, tool_lanes_json, resource_scope_json, config_json, metadata_json,
  composer_visible, settings_visible, sort_priority,
  is_enabled, setup_status, health_strategy, health_status,
  created_at, updated_at
) VALUES (
  'plg_fnf_resend',
  'ede6590ac0d2fb7daf155b35653457b2',
  'resend', 'resend', 'default', 'production',
  'api', 'communications', 'Email', 'Resend',
  'Transactional and mailbox email provider for the Ecommerce Email App.',
  'https://api.resend.com', 'http_rest', 'api_key_secret', 'RESEND_API_KEY',
  '["email.mailbox.read","email.message.read","email.send","email.provider.status","email.webhook.receive"]',
  '["email","mailbox","communications","webhooks"]',
  '{"worker":"fuelnfreetime","domain":"fuelnfreetime.com","database_binding":"DB","mailbox_table":"mail_mailboxes","message_table":"mail_messages","authorization":"owner_user_id/owner_auth_email/access_json"}',
  '{"credential_ref":"RESEND_API_KEY","mailbox_authority":"mail_mailboxes","send_route":"/api/admin/mail/send","status_route":"/api/admin/mail/resend/status"}',
  '{"family":"ecommerce-cms-agentsam","app_id":"resend"}',
  1, 1, 40,
  1, 'configured', 'provider_probe', 'unknown',
  unixepoch(), unixepoch()
)
ON CONFLICT(account_id, environment, plugin_key, installation_key) DO UPDATE SET
  provider_key = excluded.provider_key,
  category = excluded.category,
  display_name = excluded.display_name,
  short_name = excluded.short_name,
  description = excluded.description,
  endpoint_url = excluded.endpoint_url,
  transport = excluded.transport,
  auth_type = excluded.auth_type,
  secret_ref = excluded.secret_ref,
  capabilities_json = excluded.capabilities_json,
  tool_lanes_json = excluded.tool_lanes_json,
  resource_scope_json = excluded.resource_scope_json,
  config_json = excluded.config_json,
  metadata_json = excluded.metadata_json,
  is_enabled = 1,
  setup_status = excluded.setup_status,
  updated_at = unixepoch();

INSERT INTO agentsam_capabilities
(capability_key, domain, verb, description, is_mutating, is_active, created_at, updated_at)
VALUES
('campaign.overview.read','growth','read','Read campaign and attribution overview.',0,1,unixepoch(),unixepoch()),
('campaign.read','growth','read','Read campaign drafts and status.',0,1,unixepoch(),unixepoch()),
('campaign.create','growth','create','Create a campaign draft.',1,1,unixepoch(),unixepoch()),
('campaign.update','growth','update','Update a campaign draft.',1,1,unixepoch(),unixepoch()),
('campaign.generate','growth','generate','Generate the reviewable campaign pack for a draft.',1,1,unixepoch(),unixepoch()),
('campaign.publish','growth','publish','Publish approved campaign outputs.',1,1,unixepoch(),unixepoch()),
('email.mailbox.read','communications','read','List mailboxes available to the authenticated admin user.',0,1,unixepoch(),unixepoch()),
('email.message.read','communications','read','Read messages from an authorized mailbox.',0,1,unixepoch(),unixepoch()),
('email.send','communications','send','Send an email from an authorized mailbox.',1,1,unixepoch(),unixepoch()),
('email.provider.status','communications','status','Read Resend provider/domain status.',0,1,unixepoch(),unixepoch()),
('email.webhook.receive','communications','receive','Receive provider delivery/inbound webhook events.',1,1,unixepoch(),unixepoch())
ON CONFLICT(capability_key) DO UPDATE SET
  domain=excluded.domain,
  verb=excluded.verb,
  description=excluded.description,
  is_mutating=excluded.is_mutating,
  is_active=1,
  updated_at=unixepoch();

-- Internal app tools use existing admin APIs. Write tools are confirmation/approval gated.
INSERT INTO agentsam_tools (
  id, account_id, tool_name, tool_key, display_name, tool_category,
  handler_type, handler_key, description, input_schema, output_schema,
  handler_config, intent_tags, modes_json, dispatch_target,
  risk_level, requires_approval, requires_confirmation,
  route_key, workflow_key, task_type, domain, capability_key, capability_tier,
  is_active, oauth_visible, sort_priority, plugin_key, plugin_id,
  connector_access_class, app_id, resource_scope_json, operations_json,
  created_at, updated_at
) VALUES
('ast_growth_overview','ede6590ac0d2fb7daf155b35653457b2','growth_overview_read','growth_overview_read','Growth Overview',
 'growth.analytics','admin_api','growth',
 'Read current campaign, session, attribution, and revenue overview.',
 '{}','{}',
 '{"path":"/api/admin/growth/overview","method":"GET","operation":"overview.read","internal":true}',
 '["growth","campaign","marketing","attribution","revenue","performance"]','["agent","plan","ask"]','internal',
 'low',0,0,'growth','fnf_agentsam_chat','growth_read','growth','campaign.overview.read','common',
 1,0,20,NULL,NULL,'read','growth',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","database_binding":"DB","tables":["growth_campaigns","analytics_events","go_links"]}',
 '["read"]',unixepoch(),unixepoch()),

('ast_growth_campaigns_list','ede6590ac0d2fb7daf155b35653457b2','growth_campaigns_list','growth_campaigns_list','List Campaigns',
 'growth.campaigns','admin_api','growth',
 'List campaign drafts and their current status.',
 '{"type":"object","properties":{"status":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100}}}','{}',
 '{"path":"/api/admin/growth/campaigns","method":"GET","operation":"campaign.list","internal":true}',
 '["campaign","campaigns","marketing","draft"]','["agent","plan","ask"]','internal',
 'low',0,0,'growth','fnf_agentsam_chat','growth_read','growth','campaign.read','common',
 1,0,21,NULL,NULL,'read','growth',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","database_binding":"DB","tables":["growth_campaigns"]}',
 '["read"]',unixepoch(),unixepoch()),

('ast_growth_campaign_create','ede6590ac0d2fb7daf155b35653457b2','growth_campaign_create','growth_campaign_create','Create Campaign Draft',
 'growth.campaigns','admin_api','growth',
 'Create a reviewable campaign draft; does not publish outputs.',
 '{"type":"object","properties":{"name":{"type":"string"},"goal":{"type":"string"},"audience":{"type":"string"},"priority":{"type":"string"},"brief":{"type":"string"},"channels":{"type":"array","items":{"type":"string"}}},"required":["name"]}','{}',
 '{"path":"/api/admin/growth/campaigns","method":"POST","operation":"campaign.create","internal":true}',
 '["create campaign","campaign draft","marketing"]','["agent","plan"]','internal',
 'medium',0,1,'growth','fnf_agentsam_chat','growth_write','growth','campaign.create','common',
 1,0,30,NULL,NULL,'write','growth',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","database_binding":"DB","tables":["growth_campaigns"]}',
 '["create"]',unixepoch(),unixepoch()),

('ast_growth_campaign_update','ede6590ac0d2fb7daf155b35653457b2','growth_campaign_update','growth_campaign_update','Update Campaign Draft',
 'growth.campaigns','admin_api','growth',
 'Update fields on an existing campaign draft; does not publish outputs.',
 '{"type":"object","properties":{"campaign_id":{"type":"string"},"name":{"type":"string"},"goal":{"type":"string"},"audience":{"type":"string"},"priority":{"type":"string"},"brief":{"type":"string"},"channels":{"type":"array","items":{"type":"string"}}},"required":["campaign_id"]}','{}',
 '{"path_template":"/api/admin/growth/campaigns/{campaign_id}","method":"PATCH","operation":"campaign.update","internal":true}',
 '["update campaign","edit campaign","campaign draft"]','["agent","plan"]','internal',
 'medium',0,1,'growth','fnf_agentsam_chat','growth_write','growth','campaign.update','common',
 1,0,31,NULL,NULL,'write','growth',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","database_binding":"DB","tables":["growth_campaigns"]}',
 '["update"]',unixepoch(),unixepoch()),

('ast_growth_campaign_generate','ede6590ac0d2fb7daf155b35653457b2','growth_campaign_generate','growth_campaign_generate','Generate Campaign Pack',
 'growth.campaigns','admin_api','growth',
 'Generate draft campaign outputs for review; publishing remains separate.',
 '{"type":"object","properties":{"campaign_id":{"type":"string"}},"required":["campaign_id"]}','{}',
 '{"path_template":"/api/admin/growth/campaigns/{campaign_id}/generate","method":"POST","operation":"campaign.generate","internal":true}',
 '["generate campaign","campaign pack","draft marketing"]','["agent","plan"]','internal',
 'medium',0,1,'growth','fnf_agentsam_chat','growth_write','growth','campaign.generate','common',
 1,0,32,NULL,NULL,'write','growth',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","database_binding":"DB","tables":["growth_campaigns"],"workers_ai_binding":"AGENTSAM_WAI"}',
 '["generate"]',unixepoch(),unixepoch()),

('ast_growth_campaign_publish','ede6590ac0d2fb7daf155b35653457b2','growth_campaign_publish','growth_campaign_publish','Publish Campaign',
 'growth.campaigns','admin_api','growth',
 'Publish approved campaign outputs to selected channels.',
 '{"type":"object","properties":{"campaign_id":{"type":"string"},"email_mode":{"type":"string"},"test_email":{"type":"string"}},"required":["campaign_id"]}','{}',
 '{"path_template":"/api/admin/growth/campaigns/{campaign_id}/publish","method":"POST","operation":"campaign.publish","internal":true}',
 '["publish campaign","launch campaign","send campaign"]','["agent"]','internal',
 'high',1,1,'growth','fnf_agentsam_chat','growth_publish','growth','campaign.publish','elevated',
 1,0,60,NULL,NULL,'write','growth',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","database_binding":"DB","tables":["growth_campaigns"],"cms_publish":true,"email_provider":"resend"}',
 '["publish"]',unixepoch(),unixepoch()),

('ast_email_mailboxes_list','ede6590ac0d2fb7daf155b35653457b2','email_mailboxes_list','email_mailboxes_list','List My Mailboxes',
 'email.mailboxes','admin_api','mail',
 'List only mailboxes the authenticated admin user is authorized to access.',
 '{}','{}',
 '{"path":"/api/admin/mail/mailboxes","method":"GET","operation":"mailbox.list","internal":true}',
 '["email","inbox","mailbox","mailboxes"]','["agent","plan","ask"]','internal',
 'low',0,0,'content','fnf_agentsam_chat','email_read','communications','email.mailbox.read','common',
 1,0,20,'resend',(SELECT id FROM agentsam_plugins WHERE account_id='ede6590ac0d2fb7daf155b35653457b2' AND plugin_key='resend' LIMIT 1),
 'read','resend',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","mailbox_authorization":"owner_user_id/owner_auth_email/access_json","tables":["mail_mailboxes"]}',
 '["read"]',unixepoch(),unixepoch()),

('ast_email_messages_list','ede6590ac0d2fb7daf155b35653457b2','email_messages_list','email_messages_list','List Mailbox Messages',
 'email.messages','admin_api','mail',
 'List messages only from a mailbox the authenticated admin user can access.',
 '{"type":"object","properties":{"mailbox":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100},"q":{"type":"string"}}}','{}',
 '{"path":"/api/admin/mail/messages","method":"GET","operation":"message.list","internal":true}',
 '["email","inbox","messages","sent","payments"]','["agent","plan","ask"]','internal',
 'low',0,0,'content','fnf_agentsam_chat','email_read','communications','email.message.read','common',
 1,0,21,'resend',(SELECT id FROM agentsam_plugins WHERE account_id='ede6590ac0d2fb7daf155b35653457b2' AND plugin_key='resend' LIMIT 1),
 'read','resend',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","mailbox_authorization":"owner_user_id/owner_auth_email/access_json","tables":["mail_mailboxes","mail_messages"]}',
 '["read"]',unixepoch(),unixepoch()),

('ast_email_send','ede6590ac0d2fb7daf155b35653457b2','email_send','email_send','Send Email',
 'email.send','admin_api','mail',
 'Send through Resend from a mailbox the authenticated admin user is authorized to use.',
 '{"type":"object","properties":{"mailbox":{"type":"string"},"to":{"type":"string"},"subject":{"type":"string"},"body":{"type":"string"},"test":{"type":"boolean"}},"required":["mailbox","to","subject","body"]}','{}',
 '{"path":"/api/admin/mail/send","method":"POST","operation":"email.send","internal":true}',
 '["send email","reply","email customer","message customer"]','["agent"]','internal',
 'high',1,1,'content','fnf_agentsam_chat','email_send','communications','email.send','elevated',
 1,0,60,'resend',(SELECT id FROM agentsam_plugins WHERE account_id='ede6590ac0d2fb7daf155b35653457b2' AND plugin_key='resend' LIMIT 1),
 'write','resend',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","mailbox_authorization":"owner_user_id/owner_auth_email/access_json","provider":"resend","tables":["mail_mailboxes","mail_messages"]}',
 '["send"]',unixepoch(),unixepoch()),

('ast_email_provider_status','ede6590ac0d2fb7daf155b35653457b2','email_provider_status','email_provider_status','Email Provider Status',
 'email.provider','admin_api','mail',
 'Read Resend configuration and domain/webhook health status.',
 '{}','{}',
 '{"path":"/api/admin/mail/resend/status","method":"GET","operation":"provider.status","internal":true}',
 '["resend","email status","mail status","domain status"]','["agent","plan","ask"]','internal',
 'low',0,0,'content','fnf_agentsam_chat','email_read','communications','email.provider.status','common',
 1,0,22,'resend',(SELECT id FROM agentsam_plugins WHERE account_id='ede6590ac0d2fb7daf155b35653457b2' AND plugin_key='resend' LIMIT 1),
 'read','resend',
 '{"account_id":"ede6590ac0d2fb7daf155b35653457b2","provider":"resend","domain":"fuelnfreetime.com"}',
 '["status"]',unixepoch(),unixepoch())
ON CONFLICT(tool_key) DO UPDATE SET
  display_name=excluded.display_name,
  tool_category=excluded.tool_category,
  handler_type=excluded.handler_type,
  handler_key=excluded.handler_key,
  description=excluded.description,
  input_schema=excluded.input_schema,
  output_schema=excluded.output_schema,
  handler_config=excluded.handler_config,
  intent_tags=excluded.intent_tags,
  modes_json=excluded.modes_json,
  dispatch_target=excluded.dispatch_target,
  risk_level=excluded.risk_level,
  requires_approval=excluded.requires_approval,
  requires_confirmation=excluded.requires_confirmation,
  route_key=excluded.route_key,
  workflow_key=excluded.workflow_key,
  task_type=excluded.task_type,
  domain=excluded.domain,
  capability_key=excluded.capability_key,
  capability_tier=excluded.capability_tier,
  is_active=excluded.is_active,
  sort_priority=excluded.sort_priority,
  plugin_key=excluded.plugin_key,
  plugin_id=excluded.plugin_id,
  connector_access_class=excluded.connector_access_class,
  app_id=excluded.app_id,
  resource_scope_json=excluded.resource_scope_json,
  operations_json=excluded.operations_json,
  updated_at=unixepoch();

-- Correct tool-capable Workers AI registry flags from current Cloudflare model capabilities.
UPDATE agentsam_ai SET supports_tools=1, updated_at=datetime('now')
WHERE model_id IN (
  '@cf/moonshotai/kimi-k2.6',
  '@cf/moonshotai/kimi-k2.7-code',
  '@cf/openai/gpt-oss-120b',
  '@cf/openai/gpt-oss-20b',
  '@cf/zai-org/glm-4.7-flash',
  '@cf/zai-org/glm-5.2'
);

-- Repository contracts are generated separately from package-owned manifests.
