-- ctx_fuelnfreetime — worker D1 (fuelnfreetime) runtime compass
-- Apply: npm run db:seed:ctx-fuelnfreetime

INSERT OR REPLACE INTO agentsam_project_context (
  id,
  tenant_id,
  workspace_id,
  project_key,
  project_name,
  project_type,
  status,
  priority,
  description,
  goals,
  constraints,
  current_blockers,
  primary_tables,
  secondary_tables,
  workers_involved,
  r2_buckets_involved,
  domains_involved,
  mcp_services_involved,
  key_files,
  related_routes,
  notes,
  created_by,
  started_at,
  created_at,
  updated_at
) VALUES (
  'ctx_fuelnfreetime',
  'tenant_fuelnfreetime',
  'ws_fuelnfreetime',
  'fuelnfreetime',
  'Fuel & Free Time — client worker',
  'client_worker',
  'active',
  85,
  'Cloudflare Worker `fuelnfreetime` for Fuel & Free Time (Justin Molaison). Production: fuelnfreetime.com; workers.dev: fuelnfreetime.meauxbility.workers.dev. Repo: github.com/SamPrimeaux/fuelnfreetime (Connor McNeely: GitHub + Cloudflare collaborator). Stack: Workers + D1 `fuelnfreetime` (9fd6ff92-e407-4b51-8b01-3c93f3845bb2) + R2 `fuelnfreetime` (WEBSITE_ASSETS at /media/*) + KV CMS_CACHE + DO CMS_EDITOR (CmsEditorRoom live CMS) + Workers AI AGENTSAM_WAI. Commerce live: products/variants/inventory, media library, cart (localStorage), checkout v1 (D1 orders, no Stripe). CMS: D1 draft + R2 section bodies + KV publish + cms-hydrate.js. Agent Sam: admin chat + D1 agentsam_skill registry + R2 agentsam/skills/*.md. Runtime contracts: docs/RUNTIME-CONTRACTS-COMMERCE.md, docs/RUNTIME-CONTRACTS-STRIPE.md, AGENTS.md. Admin login: /admin/login (Justin jmoeee21@yahoo.com). Deploy: npm run deploy from repo root.',
  '["P0: Stripe Checkout Sessions + webhooks per RUNTIME-CONTRACTS-STRIPE.md","P1: Order confirmation email (Resend)","P1: Admin order detail API + line items","P2: CMS hydration slots on about/shop/community beyond hero","P2: Gmail OAuth for admin mail","P3: Store password / B2B gates enforcement"]',
  '["Follow docs/RUNTIME-CONTRACTS-*.md and AGENTS.md — extend contract before bypassing","D1 is SoT for catalog/orders; R2 for media + skill markdown; KV for published CMS only","Never commit secrets — wrangler secret put STRIPE_* RESEND_*","Checkout v1 decrements inventory immediately — change when Stripe ships","agentsam_skill bodies live in R2 agentsam/skills/ (retrieval_strategy=r2)","Connor agents: pull main, read AGENTS.md, npm run agentsam:skills:sync after skill edits"]',
  '["Stripe not wired — checkout creates pending orders without payment","Order confirmation email not sent","Admin orders list has no line-item detail endpoint","Gmail OAuth stubbed in mail UI","Store password prefs saved but not enforced on storefront"]',
  'products,product_variants,product_images,orders,order_items,media_assets,pages,page_sections,agentsam_skill,agentsam_skill_file,agentsam_hook,agentsam_webhooks,agentsam_webhook_events,agentsam_mcp_workflows,store_settings,auth_users,auth_sessions',
  'newsletter_subscribers,mail_settings,agentsam_project_context',
  'fuelnfreetime',
  'fuelnfreetime',
  'fuelnfreetime.com,www.fuelnfreetime.com,fuelnfreetime.meauxbility.workers.dev',
  NULL,
  'AGENTS.md,docs/RUNTIME-CONTRACTS-COMMERCE.md,docs/RUNTIME-CONTRACTS-STRIPE.md,docs/AGENTSAM-SKILLS.md,src/index.js,src/store/api.js,src/admin/api.js,src/cms/api.js,src/cms/registry.js,src/agentsam/skills.js,scripts/sync-agentsam-skills.mjs,wrangler.toml',
  '/api/store/products,/api/store/checkout,/api/cms/pages/:slug,/api/admin/*,/admin/login,/admin/products,/admin/pages,/shop.html,/cart.html',
  'Worker D1 canonical ctx row (ctx_fuelnfreetime). IAM platform mirror: same id on inneranimalmedia-business for Agent Sam router. Layer 0 prompt inject — not vector search.',
  'au_fnf_system',
  unixepoch(),
  COALESCE((SELECT created_at FROM agentsam_project_context WHERE id = 'ctx_fuelnfreetime'), unixepoch()),
  unixepoch()
);
